services:
  backend:
    build:
      context: .
      dockerfile: infra/docker/backend.Dockerfile
    environment:
      - DATABASE_URL=sqlite:///./app.db
      - CORS_ORIGINS=http://localhost:5173
    volumes:
      - db_data:/app/app.db
    healthcheck:
      test: ["CMD", "python", "-c", "import socket; import sys; import time; import urllib.request as u; u.urlopen('http://localhost:8000/docs'); print('ok')"]
      interval: 10s
      timeout: 5s
      retries: 5
  frontend:
    build:
      context: .
      dockerfile: infra/docker/frontend.Dockerfile
    environment:
      - VITE_API_URL=/api
    ports:
      - "8080:80"
    depends_on:
      - backend
volumes:
  db_data:
